import {
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ClipboardCheck,
  Copy,
  CornerDownLeft,
  CreditCard,
  Download,
  Edit2Icon,
  ExternalLink,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  Link2,
  Linkedin,
  Loader2,
  Moon,
  MoreVertical,
  MoreVerticalIcon,
  PieChart,
  Pizza,
  Plus,
  Terminal,
  QrCode,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  AlertCircle,
  X,
} from 'lucide-react';

export const Icons = {
  pieChart: PieChart,
  externalLink: ExternalLink,
  arrowDownLeft: CornerDownLeft,
  link2: Link2,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  trash: Trash,
  post: FileText,
  Terminal: Terminal,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  alertCircle: AlertCircle,
  user: User,
  arrowRight: ArrowRight,
  arrowLeft: ArrowLeft,
  help: HelpCircle,
  pizza: Pizza,
  twitter: Twitter,
  check: Check,
  copy: Copy,
  copyDone: ClipboardCheck,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  linkedin: Linkedin,
  moreVertical: MoreVerticalIcon,
  edit: Edit2Icon,
  qrCode: QrCode,
  download: Download,
};
